title = "Configuración básica Gitleaks"

[[rules]]
description = "Detección de passwords"
regex = '''(password|pwd)=['"][^'"]+['"]'''
tags = ["password"]

[[rules]]
description = "API keys genéricas"
regex = '''(api_key|apikey)=['"][^'"]+['"]'''
tags = ["api-key"]
