title = "Configuración Gitleaks"

[[rules]]
id = "no-passwords"
description = "No subir passwords en el código"
regex = '''(password|pwd)=['"][^'"]+['"]'''

[[rules]]
id = "no-api-keys" 
description = "No subir API keys"
regex = '''(api_key|apikey)=['"][^'"]+['"]'''
