name: Security Scan

on: [push, pull_request]

jobs:
  gitleaks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Run Gitleaks
        uses: zricethezav/gitleaks-action@v2
        env:
          GITLEAKS_CONFIG: .gitleaks.toml
