name: Tarea44 pipeline

on: [push]

jobs:
  seguridad:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Buscar secretos con Gitleaks
        uses: zricethezav/gitleaks-action@v2
        with:
          config-path: .gitleaks.toml
          
      - name: Construir imagen Docker
        run: docker build -t tarea44-app .
        
      - name: Escanear con Trivy (versión optimizada)
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'tarea44-app'
          format: 'table'
          exit-code: 0
          severity: 'CRITICAL,HIGH'
