name: Tarea44

on:
  push:
    branches: [ main ]

jobs:
  buscar-secretos:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Buscar secretos con Gitleaks
      uses: zricethezav/gitleaks-action@v2

  escanear-docker:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Construir imagen Docker
      run: docker build -t mi-app .
        
    - name: Escanear con Trivy
      run: |
        docker run --rm \
        aquasec/trivy image mi-app \
        --severity HIGH,CRITICAL \
        --exit-code 1
