name: Tarea44

on: [push]

jobs:
  seguridad:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Buscar secretos con Gitleaks
        uses: zricethezav/gitleaks-action@v2
        with:
          config-path: .gitleaks.toml
          
      - name: Construir imagen Docker
        run: docker build -t tarea44-app .
        
      - name: Escanear con Trivy
        run: |
          docker run --rm \
          aquasec/trivy image mi-app \
          --severity HIGH,CRITICAL \
          --exit-code 0
